### ISSUE TITLE
getting "com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission" when doing backup or restore using google rest api in my oneplus7 but it works in Honor4x

### ISSUE THREAD

**Issue by ajinkya976** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#75]
i am doing backup and restore using google drive rest api. it is working well in my Honor4x but it is giving me error on my oneplus7 mobile phone on below line.

**mDriveService.files().list().setSpaces("drive").execute());**

**Error :** 

```
 com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException
        at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:297)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:476)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:409)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:526)
        at com.example.mycuecards.DriveServiceHelper.lambda$queryFiles$3$DriveServiceHelper(DriveServiceHelper.java:134)
        at com.example.mycuecards.-$$Lambda$DriveServiceHelper$1AtczZDeP0wGGlvtm5L-N763xeY.call(Unknown Source:2)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission
        at com.google.android.gms.auth.zze.zzb(Unknown Source:13)
        at com.google.android.gms.auth.zzd.zza(Unknown Source:77)
        at com.google.android.gms.auth.zzd.zzb(Unknown Source:20)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:7)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:5)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source:2)
        at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source:55)
        at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:267)
        at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:292)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868) 
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:476) 
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:409) 
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:526) 
        at com.example.mycuecards.DriveServiceHelper.lambda$queryFiles$3$DriveServiceHelper(DriveServiceHelper.java:134) 
        at com.example.mycuecards.-$$Lambda$DriveServiceHelper$1AtczZDeP0wGGlvtm5L-N763xeY.call(Unknown Source:2) 
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

Kindly help on above.

**Comment by ajinkya976** [comment]
> i am doing backup and restore using google drive rest api. it is working well in my Honor4x but it is giving me error on my oneplus7 mobile phone on below line.
> 
> **mDriveService.files().list().setSpaces("drive").execute());**
> 
> **Error :**
> 
> ```
>  com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException
>         at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:297)
>         at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:476)
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:409)
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:526)
>         at com.example.mycuecards.DriveServiceHelper.lambda$queryFiles$3$DriveServiceHelper(DriveServiceHelper.java:134)
>         at com.example.mycuecards.-$$Lambda$DriveServiceHelper$1AtczZDeP0wGGlvtm5L-N763xeY.call(Unknown Source:2)
>         at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission
>         at com.google.android.gms.auth.zze.zzb(Unknown Source:13)
>         at com.google.android.gms.auth.zzd.zza(Unknown Source:77)
>         at com.google.android.gms.auth.zzd.zzb(Unknown Source:20)
>         at com.google.android.gms.auth.zzd.getToken(Unknown Source:7)
>         at com.google.android.gms.auth.zzd.getToken(Unknown Source:5)
>         at com.google.android.gms.auth.zzd.getToken(Unknown Source:2)
>         at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source:55)
>         at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:267)
>         at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:292)
>         at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868) 
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:476) 
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:409) 
>         at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:526) 
>         at com.example.mycuecards.DriveServiceHelper.lambda$queryFiles$3$DriveServiceHelper(DriveServiceHelper.java:134) 
>         at com.example.mycuecards.-$$Lambda$DriveServiceHelper$1AtczZDeP0wGGlvtm5L-N763xeY.call(Unknown Source:2) 
>         at com.google.android.gms.tasks.zzv.run(Unknown Source:2) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:764) 
> ```
> 
> Kindly help on above.

can someone please help on this issue.

**Comment by AnanthaKrish** [comment]
@ajinkya976 Hi, I think this issue is not related to IBM Core plugin. Could you please raise this in Cordova or GoogleDrive github ?
